skip_non_tags: false
#test: off
image: Visual Studio 2019
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
  - ps: ipconfig /all
  - ps: cat C:\Windows\System32\drivers\etc\hosts
  # - ps: ping -n 3 host.docker.internal
  - ps: docker version
  - ps: Switch-DockerLinux
  - ps: ipconfig /all
  - ps: cat C:\Windows\System32\drivers\etc\hosts
  # - ps: ping -n 3 host.docker.internal
  - ps: docker version
  - ps: docker run -it --rm busybox ifconfig
  - ps: docker run -it --rm busybox cat /etc/hosts
  - ps: docker run -it --rm busybox cat /etc/resolv.conf
  - ps: docker run -it --rm busybox ping -c 3 host.docker.internal
  - ps: docker run -it --rm busybox ping -c 3 docker.for.win.localhost
  - ps: dotnet tool install -g GitVersion.Tool
  - ps: dotnet tool install -g dotnet-format
  - ps: dotnet tool install -g dotnet-sonarscanner -v:m

before_build:
  - nuget restore
 # - ps: dotnet format --check --dry-run
  - ps: dotnet gitversion /l console /output buildserver
  - ps: dotnet sonarscanner begin /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=e220dd372506f00fe34923f011ea45f8568e9bcc /k:mariotoffia_FluentDocker /o:mariotoffia /v:"$env:APPVEYOR_BUILD_NUMBER" /d:sonar.cs.opencover.reportsPaths="./output/coverage.opencover.xml" /d:sonar.coverage.exclusions="**Tests*.cs"
  - ps: $env:good_to_deploy="true"
  - ps: if (Test-Path env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH) {echo "Not going to deploy because pull request."}
  - ps: if (Test-Path env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH) {$env:good_to_deploy="false"}
  - echo good_to_deploy=%good_to_deploy%

build:
  publish_nuget: true
  verbosity: minimal

test_script:
  - ps: dotnet test --settings coverletArgs.runsettings --filter TestCategory=CI -f netcoreapp3.0

after_test:
  - ps: dotnet sonarscanner end /d:sonar.login=e220dd372506f00fe34923f011ea45f8568e9bcc

artifacts:
  - path: '.\**\Release\*.nupkg'
    name: NuGet Packages

deploy:
  - provider: NuGet
    on:
      branch: master
      good_to_deploy: true
    api_key:
      secure: 7nuJgcCxoCbPZRW7ZeOUNFC3myB1AsCJN4O2UOT3D+TRKOLyUG0b6isOeW64FOa+
