skip_non_tags: false
test: off
image: Visual Studio 2019
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
  - ps: dotnet tool install -g Codecov.Tool
  - ps: dotnet tool install -g GitVersion.Tool
  - ps: dotnet tool install -g dotnet-format

before_build:
  - nuget restore
  - ps: dotnet format --check --dry-run
  - ps: dotnet gitversion /l console /output buildserver

build:
  publish_nuget: true
  verbosity: minimal

artifacts:
  - path: 'src\**\Release\*.nupkg'
    name: NuGet Packages
  - path: 'src\**\Release\*.snupkg'
    name: NuGet Symbol Packages

deploy:
  - provider: NuGet
    on:
      branch: master
    api_key:
      secure: 7nuJgcCxoCbPZRW7ZeOUNFC3myB1AsCJN4O2UOT3D+TRKOLyUG0b6isOeW64FOa+
